#!/bin/bash

# This file is part of pnglatex <https://github.com/mneri/pnglatex>.
# Copyright Massimo Neri <hello@mneri.me> and all the contributors.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# If the command is called with no arguments, then use clipboard
if [ -z "$*" ]; then
    clip="$(wl-paste)"
# Otherwise forward the arguments to pnglatex
else
    clip="$*"
fi
pnglatex -d 300 -f "$clip" -o .temp.png -e align* -p amssymb:amsmath:cancel -S
wl-copy < .temp.png
rm .temp.png
