#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

BACKGROUND=Transparent
FNAME=`date +%s%N`.png
DISPLAY=\$
PACKAGES=
SIZE=11

while getopts b:df:o:p:s: ARG; do
    case $ARG in
	b)
	    BACKGROUND=$OPTARG
	    ;;
	d)
	    DISPLAY=\$\$
	    ;;
	f)
	    FORMULA=$OPTARG
	    ;;
	o)
	    FNAME=$OPTARG
	    ;;
	p)
	    IFS=":"
	    PLIST=($OPTARG)
	    
	    for P in $PLIST; do
		PACKAGES=$PACKAGES\\usepackage{$P}
	    done
	    ;;
	s)
	    SIZE=$OPTARG
    esac
done

if [ ! "$FORMULA" ]; then
    echo "No input formula."
    exit 0
fi

BNAME=${FNAME##*/}
TMPDIR=/tmp/me/mneri/pnglatex

if [ ! -d $TMPDIR ]; then
    mkdir -p $TMPDIR
fi

PREFIX="\documentclass[${SIZE}pt]{article}$PACKAGES\pagestyle{empty}\begin{document}$DISPLAY"
SUFFIX="$DISPLAY\end{document}"

echo $PREFIX$FORMULA$SUFFIX > $TMPDIR/$BNAME.tex
latex -halt-on-error -output-directory=$TMPDIR $TMPDIR/$BNAME.tex > /dev/null

if [ $? -ne 0 ]; then
    sed -n '/^!/,/^ /p' < $TMPDIR/$BNAME.log
    exit 1
fi

dvipng -bg $BACKGROUND -o $FNAME -q -T tight -z 9 $TMPDIR/$BNAME.dvi > /dev/null
rm $TMPDIR/$BNAME.aux $TMPDIR/$BNAME.dvi $TMPDIR/$BNAME.log $TMPDIR/$BNAME.tex > /dev/null
