#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FNAME=`echo $RANDOM | md5sum`
FNAME=${FNAME:0:32}
PREFIX='\documentclass[10pt]{article}\pagestyle{empty}\begin{document}$'
FORMULA=$1
SUFFIX='$\end{document}'

echo $PREFIX $FORMULA $SUFFIX > $FNAME.tex
latex $FNAME.tex
dvipng -bg Transparent -o $FNAME.png -q -T tight -z 9 $FNAME.dvi
rm $FNAME.aux $FNAME.dvi $FNAME.log $FNAME.tex
